#!/usr/bin/env bash
# ls-updates for Waybar

PACMAN=$(checkupdates 2>/dev/null | wc -l)
YAY=$(yay -Qu 2>/dev/null | wc -l)
FLATPAK=$(flatpak update --dry-run 2>/dev/null | grep -c 'Updating')

TOTAL=$((PACMAN + YAY + FLATPAK))

# decide class based on number of updates
if [ "$TOTAL" -eq 0 ]; then
    CLASS="ok"
elif [ "$TOTAL" -le 10 ]; then
    CLASS="warn"
else
    CLASS="critical"
fi

echo "$TOTAL updates"
echo "{\"tooltip\":\"Pacman: $PACMAN\\nYay: $YAY\\nFlatpak: $FLATPAK\", \"class\":\"$CLASS\"}"
